# Generated by Django 2.1.7 on 2019-03-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_auto_20190326_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
