# Generated by Django 2.1.7 on 2019-09-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0004_auto_20190904_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='hurricane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damages', models.CharField(max_length=150)),
                ('rainfall', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
